<a href="https://colab.research.google.com/github/yujeongshinn/lab0-yujeongshinn/blob/master/Laboratory_2_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratory #2

* Name: yujeongshin
* Student ID: 202027013

Answer the questions or complete the tasks below, use the specific method described if applicable.

**What is 9 to the power of 6?**

In [ ]:
9**6

531441

**Split this string:**

    st = "Modeling of Estimation for Weather Change!"
    
**into a list.**

In [ ]:
st = "Modeling of Estimation for Weather Change!"

In [ ]:
st.split(" ")

['Modeling', 'of', 'Estimation', 'for', 'Weather', 'Change!']

**Given the variables:**

    space_station = "Death Star I"
    diameter = 120

**Use .format() to print the following string:**

    The diameter of Death Star I is 120 kilometers.

In [ ]:
space_station = "Death Star I"
diameter = 120

In [ ]:
print("The diameter of ", end = space_station)
print(" is 120 kilometers", end = ".")

The diameter of Death Star I is 120 kilometers.

**Given this nested list, use indexing to grab the word "Weather Change!"**

In [ ]:
lst = [12,13,[14,15],[16,[17,18,['Weather Change!']],19,20],21,22]

In [ ]:
lst[3][1][2][0]

'Weather Change!'

**Given this nest dictionary grab the word "Weather Change!". Be prepared, this will be annoying/tricky**

In [ ]:
d = {'key1':[1,2,3,{'key1_1':['Modeling','of','Estimation',{'key1_2':[1,2,3,'Weather Change!']}]}]}

In [ ]:
d['key1'][3]['key1_1'][3]['key1_2'][3]

'Weather Change!'

** What is the main difference between a tuple and a list?**

In [ ]:
# Tuple is immutable

**Create a function that grabs the user id from an email address from a string in the form:**

    user@domain.com
    
**So for example, passing "user@domain.com" would return: user**

In [ ]:
def userGet(email):
  return email.split('@')[0]

In [ ]:
userGet('user@domain.com')

'user'

**Create a basic function that returns True if the word 'weather' is contained in the input string. ('weather' or 'Weather')**

In [ ]:
def findWeather(st):
  return 'weather' in st.lower().split()

In [ ]:
findWeather('Is there a Weather in this sentence?')

True

**Create a function that counts the number of times the word "weather" occurs in a string. Ignore edge cases.**

In [ ]:
def countWeather(st):
  count = 0
  for word in st.lower().split():
    if word == 'weather':
      count += 1
  return count

In [ ]:
countWeather('This weather is better than the weather of yesterday!')

2

**Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 'w'. For example:**

    seq = ['dog','apple','word','weather','funny']

**should be filtered down to:**

    ['word','weather']

In [ ]:
seq = ['dog','apple','word','weather','funny']

In [ ]:
list(filter(lambda word: word[0]=='w',seq))

['word', 'weather']

**Write a Python function to reverse a string**

    s = '1234567890abcdefghijk' 

**should be shown:**

    'kjihgfedcba0987654321'

In [ ]:
s = '1234567890abcdefghijk'
string_reverse(s)

NameError: ignored

In [ ]:
string_reverse('RADAR')

NameError: ignored

In [ ]:
string_reverse('Laboratory 2')

NameError: ignored

# You finished your laboratory. Congratulations!~

### Numpy
Install :
   conda install numpy
   pip install numpy

In [ ]:
import numpy as np

## Numpy Arrays
Vectors, arrays, matrices, and number generation
Numpy arrays : vectors and matrices.
Vectors: 1-d arrays
Matrices: 2-d arrays

### Creating Numpy Arrays

In [ ]:
my_list = [1,2,3,4]

In [ ]:
print(my_list)

[1, 2, 3, 4]


In [ ]:
np.array(my_list)

array([1, 2, 3, 4])

In [ ]:
my_matrix = [(1,2,3),(4,5,6),(7,8,9)] # 3x3
print(my_matrix)

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]


In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods
### arange
Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,10)    #[0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
### zeros and ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Returns evenly spaced numbers over a specified interval

In [ ]:
np.linspace(0,10,3)    #[0,10]

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
### rand

In [ ]:
np.random.rand(2)    #[0,1)

array([0.68593042, 0.70934   ])

In [ ]:
np.random.rand(5,5)

array([[0.24269696, 0.11757248, 0.01240408, 0.13463228, 0.86814224],
       [0.57935274, 0.26528063, 0.88172727, 0.77809596, 0.17673481],
       [0.82178928, 0.98417953, 0.78540104, 0.72277157, 0.66517233],
       [0.29783596, 0.67575527, 0.1673044 , 0.38474683, 0.14063969],
       [0.60612661, 0.97779551, 0.91373987, 0.97615777, 0.5806677 ]])

### randint

In [ ]:
np.random.randint(1,1000)  #[1,100)

921

In [ ]:
np.random.randint(1,100,10)

array([39, 34, 85, 22, 80, 80, 38, 23, 84, 64])

## Array Attributes and Methods

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
ranarr

array([16, 25,  8, 28, 45, 32, 12,  5, 33,  1])

## Reshape


In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### max, min, argmax, argmin

In [ ]:
ranarr

array([16, 25,  8, 28, 45, 32, 12,  5, 33,  1])

In [ ]:
ranarr.max()

45

In [ ]:
ranarr.argmax()

4

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmin()

9

## Shape

In [ ]:
# Vactor
arr.shape

(25,)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

## dtype

In [ ]:
arr.dtype

dtype('int64')

### Indexing and Selection

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
#Get values in a range 
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:4]

array([0, 1, 2, 3])

### Broadcasting

In [ ]:
#Setting a value in index range
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
slice_arr = arr[0:6]

In [ ]:
print(slice_arr)

[0 1 2 3 4 5]


In [ ]:
#change slice
slice_arr[:] = 99

In [ ]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[0:6]=20
print(arr_copy)

[20 20 20 20 20 20  6  7  8  9 10]


In [ ]:
print(arr)
print(arr_copy)

[99 99 99 99 99 99  6  7  8  9 10]
[20 20 20 20 20 20  6  7  8  9 10]


### Indexing 2d matrices

*   matrix[row][col]
*   matrix[row,col]   <<< we will use more this style



In [ ]:
matrix = np.array(([5,10,15],[20,25,30],[35,40,45]))
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing a row
matrix[1]

array([20, 25, 30])

In [ ]:
#get an individual element value
matrix[1][0]

20

In [ ]:
#get an individual element value
matrix[1,0]

20

In [ ]:
#2d slicing
#Obtain the top right corner
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#shape bottom row
matrix[2]

array([35, 40, 45])

In [ ]:
matrix[2,:]

array([35, 40, 45])

### Fancy Indexing

In [ ]:
matrix_2 = np.zeros((10,10))

In [ ]:
matrix_2_len = matrix_2.shape[1]

In [ ]:
print(matrix_2_len)

10


In [ ]:
for i in range(matrix_2_len):
  matrix_2[i] = i
matrix_2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
matrix_2[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
matrix_2[[6,4,3,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

### Selection

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr<2]

array([1])

In [ ]:
x = 3
arr[arr>=x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Arithmetic

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr)

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])