<a href="https://colab.research.google.com/github/yujeongshinn/lab0-yujeongshinn/blob/master/Laboratory_3_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratory #3

* Name: YujeongShin
* Student ID: 202027013

Answer the questions or complete the tasks below, use the specific method described if applicable. 

Submition: Before November 5th 2020.

# NumPy Exercises

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 25 zeros 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 25 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 25 fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 25 to 50

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

array([0.38479114])

#### Use NumPy to generate an array of 100 random numbers sampled from a standard normal distribution

array([ 0.56777835,  0.45514109, -0.13247131, -1.46879298, -1.96254823,
       -0.47363334,  0.4533451 , -0.1828833 , -1.58219766,  0.90522152,
        1.05304431,  0.6699695 , -2.01772694, -1.44865297, -1.00492216,
        0.74444068,  0.25328701, -1.070886  , -1.33117528, -0.17303673,
        0.85256978,  2.00425318,  2.5278674 , -1.56272794,  0.82611452,
       -1.28100817, -0.57987734, -0.12091739, -0.04782196,  0.9336601 ,
        2.53651717, -0.89024551,  0.82428403,  0.55941047,  0.59832506,
       -1.50066803,  0.58245865, -1.56818354, -1.0585481 , -1.21739776,
        0.28339051, -0.1981468 , -0.83223051,  0.27610035,  0.12368956,
       -0.07857922,  1.3070983 ,  1.40757837, -1.1142244 , -1.1256018 ,
       -2.25142339,  1.09953246,  0.30127702,  1.39652035,  0.28101922,
        0.4973798 ,  0.68453039, -1.22372321, -0.20564317,  2.01168896,
        1.58488315,  0.132111  , -0.61738024,  0.38831856, -1.49142329,
        0.24896618, -1.47338299,  0.86091719, -1.20255354, -0.16

#### Create an array of 25 linearly spaced points between 0 and 1:

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
matrix = np.arange(1,50).reshape(7,7)
matrix

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20, 21],
       [23, 24, 25, 26, 27, 28],
       [30, 31, 32, 33, 34, 35],
       [37, 38, 39, 40, 41, 42],
       [44, 45, 46, 47, 48, 49]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

26

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 9],
       [16]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([29, 30, 31, 32, 33, 34, 35])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

#### Get the sum of all the values in matrix

1225

#### Get the standard deviation of the values in matrix

14.142135623730951

#### Get the sum of all the columns in matrix

array([154, 161, 168, 175, 182, 189, 196])

# You done with your laboratory congrats!!

# Let's start with Pandas

## Series 

In [ ]:
import numpy as np
import pandas as pd

### Create a Series

In [ ]:
labels = ['a','b','c']
my_list = [10,20,30] #list
arr = np.array([10,20,30]) #numpy array
d = {'a':10, 'b':20, 'c':30} #dictionary

Using list

In [ ]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(data = my_list, index = labels)


a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

**dictionary**

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Data in Series

In [ ]:
pd.Series(data = labels)

0    a
1    b
2    c
dtype: object

In [ ]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

### Index

In [ ]:
ser1 = pd.Series([1,2,3,4], index=['Incheon', 'Suwon', 'Seoul', 'Busan'])

In [ ]:
ser1

Incheon    1
Suwon      2
Seoul      3
Busan      4
dtype: int64

In [ ]:
ser2 = pd.Series([1,2,5,4], index = ['Incheon', 'Suwon', 'Seoul', 'Busan'])

In [ ]:
ser1['Incheon']

1

In [ ]:
ser1 + ser2

Incheon    2
Suwon      4
Seoul      8
Busan      8
dtype: int64

## DataFrames

In [ ]:
from numpy.random import randn
np.random.seed(101)

In [ ]:
df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns='W X Y Z'.split())

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### Selection and Indexing

In [ ]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
#Pass a list of column names
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [ ]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
type(df['W'])

pandas.core.series.Series



> 들여쓴 블록



In [ ]:
df['new'] = df['W'] + df['Y']

In [ ]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

**removing column**

In [ ]:
df.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
#drop a row
print(df.drop('E', axis=0))

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057


In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

**selecting rows**

In [ ]:
#.loc
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [ ]:
#loc
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

###Select subset of rows and colums

In [ ]:
df.loc['B','Y']

-0.8480769834036315

In [ ]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

**Conditional Selection**

In [ ]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [ ]:
df [df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [ ]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [ ]:
# l &
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

## Index hierachy

In [ ]:
df

W         X         Y         Z
A  0.586847 -1.621348  0.677535  0.026105
B -1.678284  0.333973 -0.532471  2.117727
C  0.197524  2.302987  0.729024 -0.863091
D  0.305632  0.243178  0.864165 -1.560931
E -0.251897 -0.578120  0.236996  0.200780

In [ ]:
#Reset to default 0,1,.....,n index
df.reset_index()

index         W         X         Y         Z
0     A  0.586847 -1.621348  0.677535  0.026105
1     B -1.678284  0.333973 -0.532471  2.117727
2     C  0.197524  2.302987  0.729024 -0.863091
3     D  0.305632  0.243178  0.864165 -1.560931
4     E -0.251897 -0.578120  0.236996  0.200780

In [ ]:
newind = 'Incheon Seoul Busan Jeju Suwon'.split()

In [ ]:
df['Cities'] = newind

In [ ]:
df

W         X         Y         Z   Cities
A  0.586847 -1.621348  0.677535  0.026105  Incheon
B -1.678284  0.333973 -0.532471  2.117727    Seoul
C  0.197524  2.302987  0.729024 -0.863091    Busan
D  0.305632  0.243178  0.864165 -1.560931     Jeju
E -0.251897 -0.578120  0.236996  0.200780    Suwon

In [ ]:
df.set_index('Cities')

W         X         Y         Z
Cities                                         
Incheon  0.586847 -1.621348  0.677535  0.026105
Seoul   -1.678284  0.333973 -0.532471  2.117727
Busan    0.197524  2.302987  0.729024 -0.863091
Jeju     0.305632  0.243178  0.864165 -1.560931
Suwon   -0.251897 -0.578120  0.236996  0.200780

In [ ]:
df

W         X         Y         Z   Cities
A  0.586847 -1.621348  0.677535  0.026105  Incheon
B -1.678284  0.333973 -0.532471  2.117727    Seoul
C  0.197524  2.302987  0.729024 -0.863091    Busan
D  0.305632  0.243178  0.864165 -1.560931     Jeju
E -0.251897 -0.578120  0.236996  0.200780    Suwon

In [ ]:
df.set_index('Cities', inplace=True)

In [ ]:
df

W         X         Y         Z
Cities                                         
Incheon  0.586847 -1.621348  0.677535  0.026105
Seoul   -1.678284  0.333973 -0.532471  2.117727
Busan    0.197524  2.302987  0.729024 -0.863091
Jeju     0.305632  0.243178  0.864165 -1.560931
Suwon   -0.251897 -0.578120  0.236996  0.200780

##Multi-Index and Index Hierachy

In [ ]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside)) #[('G1',1).....]
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [ ]:
df = pd.DataFrame(np.random.rand(6,2), index = hier_index, columns=['A','B'])
df

A         B
G1 1  0.603498  0.454420
   2  0.313479  0.380982
   3  0.642812  0.806533
G2 1  0.130528  0.730565
   2  0.005438  0.650661
   3  0.453049  0.200645

In [ ]:
df.loc['G2']

A         B
1  0.130528  0.730565
2  0.005438  0.650661
3  0.453049  0.200645

In [ ]:
df.loc['G1'].loc[1]

A    0.603498
B    0.454420
Name: 1, dtype: float64

In [ ]:
df.index.names

FrozenList([None, None])

In [ ]:
df.index.names = ['Group','Num']

In [ ]:
df

A         B
Group Num                    
G1    1    0.603498  0.454420
      2    0.313479  0.380982
      3    0.642812  0.806533
G2    1    0.130528  0.730565
      2    0.005438  0.650661
      3    0.453049  0.200645

In [ ]:
# .xs() cross-section from the Series/ Datafram
df.xs('G1')

A         B
Num                    
1    0.603498  0.454420
2    0.313479  0.380982
3    0.642812  0.806533

In [ ]:
df.xs(['G1',1])

A    0.603498
B    0.454420
Name: (G1, 1), dtype: float64

In [ ]:
df.xs(1,level='Num')

A         B
Group                    
G1     0.603498  0.454420
G2     0.130528  0.730565

##Missing Data

In [ ]:
df = pd.DataFrame({'A':[1,2, np.nan],
                   'B':[5, np.nan, np.nan],
                   'c':[1,2,3]
                   })

In [ ]:
df

A    B  c
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna()

A    B  c
0  1.0  5.0  1

In [ ]:
df.dropna(axis=1)

c
0  1
1  2
2  3

In [ ]:
df.dropna(thresh=2)

A    B  c
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
df.fillna(value='Fill Value')

A           B  c
0           1           5  1
1           2  Fill Value  2
2  Fill Value  Fill Value  3

In [ ]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

**Group by**